export const SET_DECODE_HISTORY = 'SET_DECODE_HISTORY';
export const SET_SELECTED_DECODE_RESULTS = 'SET_SELECTED_DECODE_RESULTS';
export const SET_VARIABLES = 'SET_VARIABLES';
export const SET_SELECTED_VARIABLE = 'SET_SELECTED_VARIABLE';
